#98.page pour gerer ses podcasts
BadGeek-Dev/badgeek-v4 pull request #108
Opened 2021-06-21 16:08 UTC by AldraElonal

2021-07-10 10:06 UTC, Nemotaku requested changes

2021-07-10 10:06 UTC, Nemotaku commented on application/controllers/Podcasts.php
> +		if(!isPodcasteur()) {
Créer une fonction de contrôle genre "checkIsPodcasteur" qui en cas de réponse négative renvoie à l'accueil. :)

2021-07-10 10:06 UTC, Nemotaku commented on application/controllers/Podcasts.php
> +		$podcasts = $this->podcasts_model->findByUser($this->user->id);
Que se passe t'il si $this->user est vide ? Prévoir une fonction de contrôle genre "checkIsConnected" qui en cas de réponse négative renvoie à l'accueil. :)

2021-07-10 10:06 UTC, Nemotaku commented on application/models/Podcasts_model.php
> +     $query= $this->db->get();
Pourquoi avoir supprimé le critère de validité ? Il n'était pas utilisé ailleurs ?

2021-07-10 10:06 UTC, Nemotaku commented on application/views/podcasts/podcasteurList.php
> +<table class="table_podcasteur">
Mettre en place DataTable comme dans l'admin.

2021-07-10 10:06 UTC, Nemotaku commented on assets/css/badgeek.css
> +.table_podcasteur tbody tr:hover {
DataTable pourra peut être gérer ça plutôt qu'un CSS perso ? A voir.

2021-07-10 10:06 UTC, Nemotaku commented on assets/css/badgeek.css
> -}
?

2021-07-12 09:16 UTC, AldraElonal commented on application/controllers/Podcasts.php
> +		$podcasts = $this->podcasts_model->findByUser($this->user->id);
je peux te faire la fonction de contrôle mais le checkIsConnected est géré via le IsInGroupe utilisé IsPodcasteur utilisé dans checkIsPodcasteur.
J'ai testé d'y aller directement sur indexpodcasteur sans être connecté, je suis redirigé directement à l'acceuil.

2021-07-12 21:10 UTC, merged